sudo: required
services: 
  - docker

before_install: 
  - docker build - brandonjones085/puprate-test -f ./puprate/Dockerfile ./puprate 


script: 
  - docker run brandonjones085/puprate-test npm test -- --coverage


after_success: 
  - docker build -t brandonjones085/puprate-angular ./puprate
  - docker build -t brandonjones085/puprate-express ./backend
  - docker build -t brandonjones085/puprate-mongo ./mongo


  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push brandonjones085/puprate-angular
  - docker push brandonjones085/puprate-express
  - docker push brandonjones085/puprate-mongo