version: '3'

services: 
  nginx: 
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - "80:80"

  puprate: 
    build: puprate #name of app

    volumes: 
      - ./puprate:/app
    
  express: 
    build: backend
    restart: always
    ports: 
      - "3000:3000"
    # links: 
    #   - mongo

  # mongo:
  #   container_name: mongo
  #   build: mongo
  #   ports: 
  #     - "27017:27017"
    